name: Deploy preview modpack
on:
  push:
    tags:
      - "Pre*.*.*"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/Pre}

      - name: Set the version
        run: |
          DEV=${{ steps.get_version.outputs.version }}
          sed -i -e "s/DEV/${DEV}/g" ./.minecraft/config/fancymenu/customization/tfg_version.txt
          sed -i -e "s/DEV/${DEV}/g" ./manifest.json
          sed -i -e "s/DEV/${DEV}/g" ./instance.cfg
          sed -i -e "s/DEV/${DEV}/g" ./extended/manifest.json
          sed -i -e "s/DEV/${DEV}/g" ./extended/instance.cfg

      - name: Changelog Parser RU
        id: changelog_ru
        uses: coditory/changelog-parser@v1
        with:
          path: CHANGELOG_RU.md

      - name: Changelog Parser EN
        id: changelog_en
        uses: coditory/changelog-parser@v1
        with:
          path: CHANGELOG_EN.md

      - name: normal -> extended
        run: cp -r .minecraft/* ./extended/.minecraft/

      - name: Archive Release MMC normal
        run: zip -r ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-mmc.zip ./mmc-pack.json ./instance.cfg .minecraft/

      - name: Archive Release MMC extended
        run: |
          cd ./extended/
          zip -r ../TFG-NewHorizons-${{ steps.get_version.outputs.version }}-mmc-extended.zip ./mmc-pack.json ./instance.cfg ./.minecraft/

      - name: Archive Release CF normal
        run: |
          mv -vf .minecraft/ ./overrides/ 
          zip -r ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-cf.zip ./manifest.json ./modlist.html ./overrides/bansoukou/ ./overrides/config/ ./overrides/resourcepacks/ ./overrides/shaderpacks/ ./overrides/groovy/ ./overrides/resources/ ./overrides/scripts/

      - name: Archive Release CF extended
        run: |
          cd ./extended/
          mv -vf .minecraft/ ./overrides/ 
          zip -r ../TFG-NewHorizons-${{ steps.get_version.outputs.version }}-cf-extended.zip ./manifest.json ./modlist.html ./overrides/bansoukou/ ./overrides/config/ ./overrides/resourcepacks/ ./overrides/shaderpacks/ ./overrides/groovy/ ./overrides/resources/ ./overrides/scripts/

      - name: Deleting Client Resources normal
        run: |
          cd ./overrides/
          cat ../buildtools/client_mod.txt | while read f; do rm "$f"; done
          rm -r resourcepacks resources shaderpacks

      - name: Deleting Client Resources extended
        run: |
          cd ./extended/overrides/
          cat ../../buildtools/client_mod.txt | while read f; do rm "$f"; done
          rm -r resourcepacks resources shaderpacks

      - name: Archive Release Server normal
        run: |
          cp -r ./serverfiles/* ./overrides/
          cd ./overrides/
          mv -vf ./icon.png ./server-icon.png
          zip -r ../TFG-NewHorizons-${{ steps.get_version.outputs.version }}-server.zip ./

      - name: Archive Release Server extended
        run: |
          cp -r ./serverfiles/* ./extended/overrides/
          cd ./extended/overrides/
          zip -r ../../TFG-NewHorizons-${{ steps.get_version.outputs.version }}-server-extended.zip ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: false
          generate_release_notes: false
          name: Release ${{ steps.changelog_ru.outputs.version }}
          body: ${{ steps.changelog_ru.outputs.description }}
          files: |
            ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-cf.zip
            ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-cf-extended.zip
            ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-mmc.zip
            ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-mmc-extended.zip
            ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-server.zip
            ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-server-extended.zip
