name: Deploy modpack

on:
  push:
    tags:
      - "R*.*.*"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/R}

      - name: Changelog Parser
        id: changelog
        uses: coditory/changelog-parser@v1
        with:
          path: CHANGELOG.md

      - name: normal -> extended
        run: |
          rsync -av --exclude-from='buildtools/filelist.txt' ./ ./.minecraft/
          cp -r ./.minecraft/* ./extended/.minecraft/
          cp -r ./modlist.html ./extended/modlist_temp.html
          cp -r ./manifest.json ./extended/manifest_temp.json
          sed -i -e 1,16d ./extended/manifest_temp.json
          sed 1d ./extended/modlist_temp.html
          cat ./extended/modlist_extended.html ./extended/modlist_temp.html > ./extended/modlist.html
          cat ./extended/manifest_extended.json ./extended/manifest_temp.json > ./extended/manifest.json

      - name: Set the version
        run: |
          DEV=${{ steps.get_version.outputs.version }}
          sed -i -e "s/DEV/${DEV}/g" ./extended/.minecraft/config/fancymenu/customization/tfg_version.txt
          sed -i -e "s/DEV/${DEV}/g" ./manifest.json
          sed -i -e "s/DEV/${DEV}/g" ./instance.cfg
          sed -i -e "s/DEV/${DEV}/g" ./.minecraft/config/fancymenu/customization/tfg_version.txt
          sed -i -e "s/DEV/${DEV}/g" ./extended/manifest.json
          sed -i -e "s/DEV/${DEV}/g" ./extended/instance.cfg

      - name: Archive Release MMC normal
        run: zip -r ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-mmc.zip ./mmc-pack.json ./instance.cfg .minecraft/

      - name: Archive Release MMC extended
        run: |
          cd ./extended/
          zip -r ../TFG-NewHorizons-${{ steps.get_version.outputs.version }}-mmc-extended.zip ./mmc-pack.json ./instance.cfg ./.minecraft/

      - name: Archive Release CF normal
        run: |
          mv -vf .minecraft/ ./overrides/ 
          zip -r ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-cf.zip ./manifest.json ./modlist.html ./overrides/bansoukou/ ./overrides/config/ ./overrides/resourcepacks/ ./overrides/shaderpacks/ ./overrides/groovy/ ./overrides/scripts/

      - name: Archive Release CF extended
        run: |
          cd ./extended/
          mv -vf .minecraft/ ./overrides/ 
          zip -r ../TFG-NewHorizons-${{ steps.get_version.outputs.version }}-cf-extended.zip ./manifest.json ./modlist.html ./overrides/bansoukou/ ./overrides/config/ ./overrides/resourcepacks/ ./overrides/shaderpacks/ ./overrides/groovy/ ./overrides/scripts/

      - name: Deleting Client Resources normal
        run: |
          cd ./overrides/
          cat ../buildtools/client_mod.txt | while read -r line; do find ./mods -name "$line" -delete; done
          rm -rf ./resourcepacks ./config/txloader ./shaderpacks

      - name: Deleting Client Resources extended
        run: |
          cd ./extended/overrides/
          cat ../../buildtools/client_mod.txt | while read -r line; do find ./mods -name "$line" -delete; done
          rm -rf ./resourcepacks ./config/txloader ./shaderpacks

      - name: Archive Release Server normal
        run: |
          cp -r ./buildtools/serverfiles/* ./overrides/
          cd ./overrides/
          zip -r ../TFG-NewHorizons-${{ steps.get_version.outputs.version }}-server.zip ./

      - name: Archive Release Server extended
        run: |
          cp -r ./buildtools/serverfiles/* ./extended/overrides/
          cd ./extended/overrides/
          zip -r ../../TFG-NewHorizons-${{ steps.get_version.outputs.version }}-server-extended.zip ./

      - name: Upload Curseforge normal
        uses: henkelmax/upload-curseforge-modpack-action@v1.0.0
        with:
          api-token: ${{ secrets.CF_API_TOKEN }}
          project-id: "385053"
          modpack-path: ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-cf.zip
          modpack-server-path: ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-server.zip
          changelog: "${{ steps.changelog.outputs.description }}"
          changelog-format: markdown
          game-version: "1.12.2"
          display-name: TFG-NewHorizons-${{ steps.get_version.outputs.version }}
          server-display-name: TFG-NewHorizons-${{ steps.get_version.outputs.version }}-server
          release-type: "release"

      - name: Upload Curseforge extended
        uses: henkelmax/upload-curseforge-modpack-action@v1.0.0
        with:
          api-token: ${{ secrets.CF_API_TOKEN }}
          project-id: "385053"
          modpack-path: ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-cf-extended.zip
          modpack-server-path: ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-server-extended.zip
          changelog: "${{ steps.changelog.outputs.description }}"
          changelog-format: markdown
          game-version: "1.12.2"
          display-name: TFG-NewHorizons-${{ steps.get_version.outputs.version }}-extended
          server-display-name: TFG-NewHorizons-${{ steps.get_version.outputs.version }}-server-extended
          release-type: "beta"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: false
          generate_release_notes: true
          name: Release ${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.description }}
          files: |
            ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-cf.zip
            ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-cf-extended.zip
            ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-mmc.zip
            ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-mmc-extended.zip
            ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-server.zip
            ./TFG-NewHorizons-${{ steps.get_version.outputs.version }}-server-extended.zip

      - name: Discord notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.RELEASES_1_12 }}
          username: "GitHub"
          avatar-url: https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.12.x/tree/main/resources/modpack/icons/github.png?raw=true
          embed-thumbnail-url: https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.12.x/tree/main/resources/modpack/icons/icon.png?raw=true
          embed-title: Релиз ${{ steps.changelog.outputs.version }}
          embed-description: "${{ steps.changelog.outputs.description }}"
          embed-url: https://github.com/TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x/tree/main/CHANGELOG.md
          embed-color: 15430476
          embed-footer-icon-url: https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.12.x/tree/main/resources/modpack/icons/icon.png?raw=true
          embed-footer-text: ${{ steps.changelog.outputs.date }}
