name: Deploy modpack
on:
  push:
    tags:
      - 'R*'
      - 'R*-Extended'
      - 'R*-alpha'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

      # - name: Set the version
      #   run: |
      #     MODPACKVERSION=${{ steps.get_version.outputs.VERSION }}
      #     echo "TFG-New-Horizons-${MODPACKVERSION}" > ./overrides/resources/modpack/version.txt
      #     sed -i -e "s/MODPACKVERSION/${MODPACKVERSION}/g" ./manifest.json
      #     sed -i -e "s/MODPACKVERSION/${MODPACKVERSION}/g" ./instance.cfg
      #     sed -i -e "s/MODPACKVERSION/${MODPACKVERSION}/g" ./overrides/config/fancymenu/customization/tfg_version.txt

      - name: Changelog Parser
        id: changelog
        uses: coditory/changelog-parser@v1
        with:
          path: CHANGELOG.md
          version: ${{ steps.get_version.outputs.version }}

          

      # - name: Archive Release CF
      #   run: zip -r TFG-New-Horizons-${{ steps.get_version.outputs.version }}-cf.zip ./manifest.json ./modlist.html ./overrides/bansoukou/ ./overrides/config/ ./overrides/resourcepacks/ ./overrides/groovy/ ./overrides/resources/ ./overrides/scripts/

      # - name: Archive Release MMC
      #   run: |
      #     mv -vf ./overrides/ .minecraft/
      #     cp -vf ./icon.png .minecraft/
      #     zip -r ./TFG-New-Horizons-${{ steps.get_version.outputs.version }}-mmc.zip ./mmc-pack.json ./instance.cfg .minecraft/

      # - name: Deleting Client Resources
      #   run: |
      #     cat ./buildtools/client_mod.txt | while read f; do rm "$f"; done
      #     rm -r .minecraft/resourcepacks .minecraft/resources

      # - name: Archive Release Server
      #   run: |
      #     mv -vf .minecraft/* ./serverfiles/
      #     mv -vf ./serverfiles/icon.png ./serverfiles/server-icon.png
      #     mv -vf ./serverfiles/jsg-1.12.2-4.10.1.1-server.jar ./serverfiles/mods/
      #     cd ./serverfiles/
      #     zip -r ./TFG-New-Horizons-${{ steps.get_version.outputs.version }}-server.zip ./

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: Release ${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.description }}
          files: |
            ./TFG-New-Horizons-${{ steps.get_version.outputs.version }}-cf.zip
            ./TFG-New-Horizons-${{ steps.get_version.outputs.version }}-mmc.zip
            ./serverfiles/TFG-New-Horizons-${{ steps.get_version.outputs.version }}-server.zip

      # - name: Upload Curseforge
      #   uses: henkelmax/upload-curseforge-modpack-action@v1.0.0
      #   with: 
      #     api-token: ${{ secrets.CF_API_TOKEN }}
      #     project-id: '385053'
      #     modpack-path: ./TFG-New-Horizons-${{ steps.get_version.outputs.version }}-cf.zip
      #     modpack-server-path: ./TFG-New-Horizons-${{ steps.get_version.outputs.version }}-server.zip
      #     changelog: 'Check the changes here. [Github - CHANGELOG.md](https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/blob/main/Changelog_RU.md "")' 
      #     changelog-format: markdown
      #     game-version: '1.12.2'
      #     display-name: TFG-New-Horizons-${{ steps.get_version.outputs.version }}
      #     server-display-name: TFG-New-Horizons-${{ steps.get_version.outputs.version }}-server
      #     release-type: 'release'
