name: Deploy modpack
on:
  push:
    tags:
      - 'R*'
      - 'R*-Extended'
      - 'R*-alpha'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF} | sed -e 's#refs/tags/##g' | awk -F'-' '{print $1}')

      - name: Set the version
        run: |
          MODPACKVERSION=${{ steps.get_version.outputs.VERSION }}
          echo "TFG-New-Horizons ${MODPACKVERSION}" > ./overrides/resources/custommainmenu/version.txt
          sed -i -e "s/MODPACKVERSION/${MODPACKVERSION}/g" ./manifest.json

      # - name: Read Changelog
      #   id: read_changelog
      #   uses: juliangruber/read-file-action@v1
      #   with:
      #     path: ./Changelog_RU.md

      - name: Archive Release CF
        run: zip -r TFG-New-Horizons-${{ steps.get_version.outputs.VERSION }}-cf.zip ./manifest.json ./modlist.html ./overrides/bansoukou/ ./overrides/config/ ./overrides/resourcepacks/ ./overrides/groovy/ ./overrides/resources/ ./overrides/scripts/

      - name: Archive Release Server
        run: |
          cat ./buildtools/client_mod.txt | xargs rm -rf
          mv -vf ./overrides/* ./serverfiles/
          mv -vf ./serverfiles/jsg-1.12.2-4.10.1.1-server.jar ./serverfiles/mods/
          cd ./serverfiles/
          zip -r TFG-New-Horizons-${{ steps.get_version.outputs.VERSION }}-server.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: false
          generate_release_notes: false
          files: |
            TFG-New-Horizons-${{ steps.get_version.outputs.VERSION }}-cf.zip
            TFG-New-Horizons-${{ steps.get_version.outputs.VERSION }}-server.zip

      # - name: Upload Curseforge
      #   uses: henkelmax/upload-curseforge-modpack-action@v1.0.0
      #   with: 
      #     api-token: ${{ secrets.CF_API_TOKEN }}
      #     project-id: '385053'
      #     modpack-path: ./TFG-New-Horizons-${{ steps.get_version.outputs.VERSION }}-cf.zip
      #     modpack-server-path: ./TFG-New-Horizons-${{ steps.get_version.outputs.VERSION }}-server.zip
      #     changelog: 'Check the changes here. [Github - CHANGELOG.md](https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/blob/main/Changelog_RU.md "")' 
      #     changelog-format: markdown
      #     game-version: '1.12.2'
      #     display-name: TFG-New-Horizons-${{ steps.get_version.outputs.VERSION }}
      #     server-display-name: TFG-New-Horizons-${{ steps.get_version.outputs.VERSION }}-server
      #     release-type: 'release'
