name: Notification on push EN

on: [push]

jobs:
  sending:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Changelog Parser
      id: changelog
      uses: coditory/changelog-parser@v1
      with:
        path: CHANGELOG_EN.md

    - name: Discord notification
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        username: "GitHub"
        avatar-url: https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/blob/main/normal/overrides/resources/modpack/icons/github.png?raw=true
        embed-thumbnail-url: https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/blob/main/normal/overrides/resources/modpack/icons/icon.png?raw=true
        embed-title: Релиз ${{ steps.changelog.outputs.version }}
        embed-description: "${{ steps.changelog.outputs.description }}"
        embed-url: https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/blob/main/CHANGELOG_EN.md
        embed-color: 15430476
        embed-footer-icon-url: https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/blob/main/normal/overrides/resources/modpack/icons/icon.png?raw=true
        embed-footer-text: ${{ steps.changelog.outputs.date }}
