name: Notification on push RU

on: [push]

jobs:
  sending:
    runs-on: ubuntu-latest
    steps:
    - name: Changelog Parser
      id: changelog
      uses: coditory/changelog-parser@v1
      with:
        path: ./CHANGELOG_RU.md

    - name: Discord notification
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_CHANNEL_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#48f442"
        username: "GitHub Bot"
        message: ${{ steps.changelog.outputs.description }}
        file: "./Changelog_RU.md"
