name: Notification on push RU

on: [push]

jobs:
  sending:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Changelog Parser
      id: changelog
      uses: coditory/changelog-parser@v1
      with:
        path: CHANGELOG_RU.md

    - name: Discord notification
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        username: "GitHub Bot"
        avatar-url: https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/blob/main/normal/overrides/resources/modpack/icons/github.png?raw=true
        content: "${{ steps.changelog.outputs.description }}"
        filename: CHANGELOG_RU.md
